DROP TABLE IF EXISTS product;

CREATE TABLE product(
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(127) NOT NULL,
  Description TEXT NOT NULL,
  Image_Path VARCHAR(127) NOT NULL,
  Price FLOAT NOT NULL
);
